rabbitmq:
  topicExchangeName: topic-exchange
  routingKeyName : routing.key
  directExchangeName: direct-exchange
  fanoutExchangeName: fanout-exchange
  username : guest
  password : guest
  host : rabbitmq
  port : 5672

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/producer?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /producer
